### ISSUE TITLE
Missing `visible` flag when saving / loading

### ISSUE THREAD

**Issue by jeyum2** [guillaumechereau/goxel#144]
It seems `visible` flag is missing when saving/loading for layers.
If it is just a bug, please consider the pull request #143

**Comment by guillaumechereau** [comment]
Thanks, I merged the PR.

By the way, I will be starting to ask contributors to sign a CLA (so that I keep the right to have a non GPL mobile version, or even eventually switch to MIT license in the future).  For this trivial change I don't think that's needed, but you if you don't mind, could you sill make a new PR to add your name in the list of individual CLA as described there:
https://github.com/guillaumechereau/goxel/blob/master/doc/cla/sign-cla.md
?

**Comment by jeyum2** [comment]
Thank you for merging.

I will consider sign-in, after review CLA
