### ISSUE TITLE
Goxel does not start

### ISSUE THREAD

**Issue by EvolutionPixG** [guillaumechereau/goxel#170]
When Goxel starts up, an empty console appears. After a couple of seconds of waiting, an empty editor window appears for ~0.6 seconds and then closes. No start-up errors appear.

Windows 7 x64 Professional system.
AMD video card.
AMD processor.

**Comment by EvolutionPixels** [comment]
Apparently, the main developer doesn't care so much that he's too lazy to answer. Even though the problem is serious. And changing your version of Windows 7 to Windows 10 is not the solution.

**Comment by guillaumechereau** [comment]
A few people reported this.  Unfortunately I don't have a computer with an AMD to test it!

**Comment by EvolutionPixels** [comment]
> 
> 
> A few people reported this. Unfortunately I don't have a computer with an AMD to test it!

I hope this mistake is corrected someday.

**Comment by Belonit** [comment]
same problem:
Windows 10

**Comment by BrunoSupremo** [comment]
Oh, so that is why it is not working on my new computer, it is an amd issue! ... That sucks.
Anyway we can help, maybe with some logging or report tool?

**Comment by DeathDealer33** [comment]
> Oh, so that is why it is not working on my new computer, it is an amd issue! ... That sucks.
> Anyway we can help, maybe with some logging or report tool?

Dont count on it, he doesnt help even when problems are correctly reported. He is to proud to just tell people he isnt going to fix the problem. lol Been dealing with this since V8 (over a year) and reported ever last detail when compiling myself only to be ignored for months on end. And when i finally got fed up and said something he deleted the entire thread. Just a lazy dev. laughable really drove me to making my own editorXD Just so happened to stop by again after a very long time to see if things changed, not surprised that it has not.

**Comment by guillaumechereau** [comment]
@BrunoSupremo : what would be useful is if you could compile goxel in debug and run it from a terminal, so that you might see some logs.  If you want I can put a debug build online so that you would just have to run it from a terminal.

**Comment by BrunoSupremo** [comment]
Yep, throw me the debug version and I will run it here and report back

**Comment by guillaumechereau** [comment]
I put one here: https://stellarium.sfo2.digitaloceanspaces.com/tmp/goxel-debug.zip
You can try and see if you get any useful information.

**Comment by EvolutionPixG** [comment]
> 
> 
> I put one here: https://stellarium.sfo2.digitaloceanspaces.com/tmp/goxel-debug.zip
> You can try and see if you get any useful information.

I ran your goxel debug build and it works oddly enough without any problems 😃
There were no errors in the console.

And the latest stable release of [goxel 0.10.0](https://github.com/guillaumechereau/goxel/releases/tag/v0.10.0) is still not running.

**Comment by Belonit** [comment]
I'm ready to confirm what he says EvolutionPixG. Version 0.10.0 does not work for me. debug version works without any problems.

**Comment by BrunoSupremo** [comment]
Yep, worked here too with a simple double click on the file.
---
Though the feature I was trying to use is not there anymore? The game I'm modding uses .qb files, and it animates it based on the bound box of each matrix. But I couldn't find a way to adjust the bounding box anymore. As I extended the model to one side, I have to rebalance the bound box to the other too so it keeps centered.

**Comment by guillaumechereau** [comment]
@EvolutionPixG : could you try this release build I just did as well:
https://stellarium.sfo2.digitaloceanspaces.com/tmp/goxel-0.10.5-windows.zip

It's possible the bug has been fixes by some changes since last release.  That would be nice.

@BrunoSupremo : can you open a new issue about the qb file problem?  I am not sure I understand what's the problem.

**Comment by EvolutionPixG** [comment]
> 
> 
> @EvolutionPixG : could you try this release build I just did as well:
> https://stellarium.sfo2.digitaloceanspaces.com/tmp/goxel-0.10.5-windows.zip
> 
> It's possible the bug has been fixed by some changes since last release. That would be nice.

@guillaumechereau this release build starts up and works without problems or errors 😊👍
This issue could well be closed by now. Problem solved (at least I have).

**Comment by guillaumechereau** [comment]
OK good to know.  I'll make a new release soon then.
