### ISSUE TITLE
minetest .mts support

### ISSUE THREAD

**Issue by Ygarr** [guillaumechereau/goxel#285]
Any options about support .mts schemes used in minetest?

**Comment by pegvin** [comment]
not really sure if you know this but upcoming release of [Goxel2](https://github.com/goxel2/goxel2) will be supporting minecraft & minetest's schemes.

All thanks to @bztsrc

**Comment by guillaumechereau** [comment]
Is there any documentation on the format somewhere?

**Comment by Ygarr** [comment]
> Is there any documentation on the format somewhere?
https://dev.minetest.net/Minetest_Schematic_File_Format

**Comment by guillaumechereau** [comment]
OK the format looks simple enough.  Do you have some example of files I could try?

**Comment by bztsrc** [comment]
>  Do you have some example of files I could try?

A quick websearch will reveal plenty... 

For example you can find some in my [MTS editor's repo](https://gitlab.com/bztsrc/mtsedit/-/tree/master/examples). Also look around in the [Minetest mods](https://content.minetest.net/packages/?type=mod), lots of them ship such files, they are in each mods' `schematics` subdirectory (for [example](https://notabug.org/MeseCraft/MeseCraft/src/master/mods/WORLD/shipwrecks/schematics)). And they are also attached to forum posts, like [here](https://forum.minetest.net/viewtopic.php?f=12&t=7304&start=300).

Cheers,
bzt

**Comment by Ygarr** [comment]
> OK the format looks simple enough. Do you have some example of files I could try?
Yes, of cource
[abkeep.zip](https://github.com/guillaumechereau/goxel/files/9472853/abkeep.zip)

**Comment by Ygarr** [comment]
[ranger_post_mts.zip](https://github.com/guillaumechereau/goxel/files/9472953/ranger_post_mts.zip)

**Comment by guillaumechereau** [comment]
OK I got a basic import code working.   All I need now is a mapping of all the minetest nodes id to a plain color.  I am not familiar at all with minetest.  Is there a source for that?  Or even better a way to automatically generate it from the original textures?

**Comment by Ygarr** [comment]
Think this partially can help https://wiki.minetest.net/Games/Minetest_Game/Node
But nodes id or itemstring only by url click. Also I try to look at some things that already works with mts schematics

**Comment by guillaumechereau** [comment]
OK, I guess the simpler for now is to create a 'minetest' palette manually using the wiki as a source.  I'll try to do that.  Assuming all the nodes are listed in the wiki it should be enough to get something decent when opening images for the default minetest game.

**Comment by guillaumechereau** [comment]
In the end the only proper way would be for goxel to support textured voxels, but that is way beyond the scope of the project.

**Comment by guillaumechereau** [comment]
OK actually the project minetestmapper provides a txt file with the colors for most minetest nodes, so I just used that.
I get basic import working.

![Screenshot from 2022-09-05 09-57-23](https://user-images.githubusercontent.com/107679/188345446-01a9c7e8-f8d6-4f30-81bc-cc4a2273bbc7.png)

**Comment by Ygarr** [comment]
https://gitlab.com/bztsrc/mtsedit may can help also if smth.

**Comment by bztsrc** [comment]
> I guess the simpler for now is to create a 'minetest' palette manually using the wiki as a source.

>  actually the project minetestmapper provides a txt file with the colors

The problem is, these mappings are changing *dynamically*. Minetestmapper's [color.txt](https://github.com/minetest/minetestmapper/blob/master/colors.txt) doesn't work with the most popular Mineclone2 game at all for example, and it does not support mods registered nodes either.

> https://gitlab.com/bztsrc/mtsedit may can help also if smth.

Yes, MTSEdit can generate a node mapping from an arbitrary MTS file using the GIMP Palette format. That's why in [Goxel2](https://goxel2.github.io) I've implemented node matching using .gpl files.

If someone is looking for real MTS support, I'd recommend [Goxel2](https://goxel2.github.io), as that supports Mineclone2 too and arbitrary Minetest Game mod nodes much better. Furthermore, you can select the desired mapping from the UI.

Cheers,
bzt

ps: @guillaumechereau you are such a liar. You said you won't add new formats, and I have to wait until you implement a plugin system. Yet, here we are, you haven't added Model 3D, but despite what you said, now you're trying to add MTS...

**Comment by guillaumechereau** [comment]
@bztsrs, please not this topic again...  I already explained: I only want support for well known formats.  I don't play Minetest, but it seems big enough to deserve some support from Goxel.  It is perfectly fine for you to make a fork of Goxel for your own need as long as you respect the license.

As for the topic at hand.  I can add a name matching fallback to the current palette, so that if needed users could still create their own palettes to match the colors they want.  I don't think much more is needed, as a proper minetest file editor would probably need to support textured voxels.

**Comment by pegvin** [comment]
ah calm down, @guillaumechereau i have no problem with you just copying those files from goxel2's repo, bztsrc wrote them so he might need to sign the CLA, but the implementations are quite simple you don't need to mess so much.

tbh you can just pull all the changes you want i have no problem in that, but a plugin system would help alot!

**Comment by Ygarr** [comment]
Hope "grain by grain" without burden everyone would be "satiated"

**Comment by bztsrc** [comment]
> bztsrc wrote them so he might need to sign the CLA

Which I won't. I've signed a CLA with my original M3D patch, @guillaumechereau doesn't gave a shit about that, so I definitely won't sign it for any MTS patches.

And if @guillaumechereau by any chance tries to use my M3D patch CLA for this, I'll consider this an act of theft and bad intentions.

Cheers,
bzt

**Comment by mgerhardy** [comment]
enkimi has a mapping https://github.com/dougbinks/enkiMI and vengi, too: https://github.com/mgerhardy/vengi/blob/master/src/modules/voxelformat/private/MinecraftPaletteMap.cpp
not sure though if this works for minetest, too - not much minecraft knowledge here to answer this.
