### ISSUE TITLE
using GitHub actions for ci and releases?

### ISSUE THREAD

**Issue by pegvin** [guillaumechereau/goxel#289]
Currently you build the software yourself and create a new release, the same thing can be done via GitHub actions too.

Should i make a pr for it?

**Comment by guillaumechereau** [comment]
For continuous integration currently there is a Travis hook that is supposed to test the build.  I am not sure if it still works though.  Feel free to make a PR to add a github action hook.  It would be nice to have a nightly build available for people who don't want to compile themself indeed.

As for the releases, I think I rather do them manually for now, since I have to test them anyway.  One issue with automatic release is that I need to sign the mac package, which I can only do locally I think.

**Comment by pegvin** [comment]
ah nice, will make a pr soon.

**Comment by hendursaga** [comment]
There's a stale PR for [CircleCI builds](https://github.com/guillaumechereau/goxel/pull/70), not sure how Travis, GitHub Actions, etc compare..

**Comment by guillaumechereau** [comment]
Yeah me neither.  Actually I would gladly replace Travis with GitHub, since the project is hosted here anyway.

**Comment by pegvin** [comment]
Uh um i had deleted the repository, i forgot that there was a unmerged pr, I've re-open it now.
