### ISSUE TITLE
A single question

### ISSUE THREAD

**Issue by devMidgard** [guillaumechereau/goxel#46]
Hey there! First off, thank you for creating this wonderful software, this is exactly what I was looking for for developing a "Cube World"-like game in which I needed a voxel based software to easily paint terrains etc manually.

I was wondering how did you achieve not having a voxel scene limit. Both Qubicle and MagicaVoxel have a limit in their matrices, they weren't allowing me to paint big environments from scratch, they're only good enough to create single models and animations.

How did you achieve that? And in which point will the software start to perform badly when handling huge scenes?

**Comment by guillaumechereau** [comment]
Thanks!

I don't know how magica voxel or qubicle work, so I cannot say why they don't support unlimited scene size.  In goxel the scene is internally split into many small matrices (of size 16^3), so memory is only used in the space containing voxels.  This means that what really matter is the number of non empty voxels, not the size of the scene.

That being said, if you make your scene too big, at some point tree things could happen:
- You could run out of memory to contain the scene, crashing the program.
- The program might become too slow to be usable.
- There might be a bug due to the limited number of uid used by the matrices.

So far I have never really tried to work with big models, so I cannot tell at what point it would start to be a problem.  Let me know if you encounter any bugs.

**Comment by devMidgard** [comment]
Thanks for the quick response!

That sounds great; I have tested myself with huge scenes that could make up for a big portion of "map zone" to be joined with others in my engine's editor and it works wonderfully, it kinda takes long to export but I guess it's normal due to the amount of voxels.

I will let you know if I ever run into some trouble!

Also, I haven't tested exporting to other formats other than .obj, but once importing into blender, It can't seem to read the colors I painted using Goxel (i guess due to lack of materials). Will color exporting be possible at some point? I can however go ahead and paint manually in blender.

**Comment by guillaumechereau** [comment]
In fact goxel exports the colors in obj, but not in a format that blender can open.  I am not quite sure how it has to be in order to work.  The ply export should work with blender, though the current version has a bug where the ply files are saved with an .obj extension! This is fixed in the current master branch.
