### ISSUE TITLE
Export marching cube ply/obj

### ISSUE THREAD

**Issue by guillaumechereau** [guillaumechereau/goxel#76]
Need to support exporting the marching cube model as a ply or obj.

**Comment by iperov** [comment]
I want it too

**Comment by YarlBoro** [comment]
@iperov 
I'm confused why this ticket is still open, because this feature is already implemented and **works** for both ply & obj, even with faces colour(ing). Maybe Guillaume is unsatisfied with quality of mesh or performance. This could be the case, because one of my relatively big models was exporting to .ply format for about 9 hours! But eventually it was saved properly.

**Comment by iperov** [comment]
@YarlBoro I cannot export mc with ply. How to do it?

**Comment by YarlBoro** [comment]
Go to 'Render' tab. Reveal 'Render Advanced' menu and check 'Marching Cubes'. Now in top bar go to 'File', 'Export as..', choose 'ply' or 'obj'. 
Now wait, just give it some time and Goxel will save your model.

**Comment by iperov** [comment]
@YarlBoro I tried it, nothing working, so I post there. 
![goxel_2017-12-14_17-38-00](https://user-images.githubusercontent.com/8076202/33994892-9a3a76cc-e0f5-11e7-899d-3689887fe34d.png)

**Comment by guillaumechereau** [comment]
It’s done but not available in the last release I think. I should make a
new release soon.
